version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::874930499144:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-qse4Iu3IWAcv"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::874930499144:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-LKin08eU6wIt"
cloudformation_execution_role = "arn:aws:iam::874930499144:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-vbBbcV8KivFq"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-smjryvubkcra"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::874930499144:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-zbw8LLb8p0M1"
cloudformation_execution_role = "arn:aws:iam::874930499144:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-Eb87mkBdsFRr"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-o85afhwjwhrl"
image_repository = ""
region = "us-east-1"
