version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::874930499144:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-yJDisyxBMexb"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::874930499144:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-FBuE5ltw0m91"
cloudformation_execution_role = "arn:aws:iam::874930499144:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-8wmlpFF9AbZk"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-dfjrxinq5aoo"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::874930499144:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-WmW3k9dfrD6k"
cloudformation_execution_role = "arn:aws:iam::874930499144:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-QJk2zOzpvZFD"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-bcezihmjjgkn"
image_repository = ""
region = "us-east-1"
